node_js:
    - "10"
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
install:
    - npm install
script:
    - npm run build 
cache:
    directories:
        - "node_modules"
notifications:
    email: false
deploy:
    provider: pages
    skip-cleanup: true
    local_dir: dist
    github_token: $GITHUB_TOKEN
    repo: blog4share/blog4share.github.io
    keep-history: true
    target-branch: master
    on:
        branch: master